## Run on container for speed and use trusty by default for latests packages
dist: trusty
sudo: false

language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2

# test only master (+ Pull requests)
branches:
  only:
    - master

# install dependencies
before_script:
    - phpenv config-rm xdebug.ini
    # Setup GitHub key to avoid api rate limit (pure auth read only key, no rights, for use by ez repos only!)
    - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
    # Avoid memory issues on composer install
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer update --prefer-dist --no-interaction

# execute phpunit as the script command
script:
  - php vendor/bin/phpunit --colors

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
